name: octo_image
description: A multifunctional Flutter image widget
version: 0.0.1
homepage: https://github.com/Baseflow/octo_image

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0
  transparent_image: ^1.0.0
