name: octo_image
description: A multifunctional Flutter image widget. Supports placeholders, error widgets and image transformers with fading.
version: 1.0.0-nullsafety.1
homepage: https://github.com/Baseflow/octo_image

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.5.2-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
